#!/usr/bin/env bash

set -e


FILE_NAME="console.php"
path="/usr/bin/env php"
SHEBANG="#!"
fullpath="$SHEBANG$path"
date=$(date '+%d-%m-%y %H:%M:%S')
PHP_START="<?php"

function printContent {
{
printf '%s\n' "$fullpath"
printf '%s\n' "$PHP_START"
printf 'echo \"PHP application generated by Bash script on %s\";\n' "$date"

} > $1
}

if [[  -z "$1"  ]]; then

touch $FILE_NAME
chmod u+x $FILE_NAME

printContent $FILE_NAME

else

filename=$1
touch $filename
chmod u+x $filename

printContent  $filename

fi
