#!/usr/bin/env bash

set -e


FILE_NAME="console.php"
 shebang="#!/usr/bin/env php"
date=$(date '+%d-%m-%y %H:%M:%S')
PHP_START="<?php"
PHP_END="?>"
if [[  -z "$1"  ]]; then

touch $FILE_NAME
chmod u+x $FILE_NAME
{
printf '%s\n' "$shebang"
printf '%s\n' "$PHP_START"
printf 'echo \"PHP application generated by Bash script on %s\"\n' "$date"
printf '%s\n' "$PHP_END"

}> $FILE_NAME

else

filename=$1".sh"
touch $filename
chmod u+x $filename

{
printf '%s\n' "$shebang"
printf '%s\n' "$PHP_START"
printf 'echo \"PHP application generated by Bash script on %s\"\n' "$date"
printf '%s\n' "$PHP_END"

}> $filename

fi